add RDS data refresh helm job
ministryofjustice/hmpps-delius-operational-automation pull request #476
Opened 2024-11-20 16:09 UTC by sobostion

2024-11-20 16:44 UTC, andrewmooreio reviewed
Other parameters such as RDS instance name and the secret names will need to be templated using the component name/environment. But given we don't know what they're called yet, not sure what else can be done. This ticket should probably have waited until we have the necessary k8s resources to build on top of in hindsight!

2024-11-20 17:45 UTC, georgepstaylor approved these changes

2024-11-20 21:35 UTC, georgepstaylor requested changes
As per @andrewmooreio's comment, I think this should do the trick?

2024-11-20 21:35 UTC, georgepstaylor commented on helm/refresh-db/templates/job.yaml
> +                  name: rds-instance-output-{{ .Values.destinationEnvironment }}
```suggestion
                  name: rds-instance-output-{{ .Values.destinationEnvironment }}-{{ .Values.component }}
```

2024-11-20 21:35 UTC, georgepstaylor commented on helm/refresh-db/templates/job.yaml
> +                  name: rds-instance-output-{{ .Values.destinationEnvironment }}
```suggestion
                  name: rds-instance-output-{{ .Values.destinationEnvironment }}-{{ .Values.component }}
```

2024-11-20 21:35 UTC, georgepstaylor commented on helm/refresh-db/templates/job.yaml
> +                  name: rds-instance-output-{{ .Values.destinationEnvironment }}
```suggestion
                  name: rds-instance-output-{{ .Values.destinationEnvironment }}-{{ .Values.component }}
```

2024-11-20 21:35 UTC, georgepstaylor commented on helm/refresh-db/templates/job.yaml
> +                  name: rds-instance-output-{{ .Values.destinationEnvironment }}
```suggestion
                  name: rds-instance-output-{{ .Values.destinationEnvironment }}-{{ .Values.component }}
```

2024-11-20 21:35 UTC, georgepstaylor commented on helm/refresh-db/templates/job.yaml
> +                  name: rds-instance-output
```suggestion
                  name: rds-instance-output-{{ .Values.component }}
```

2024-11-20 21:35 UTC, georgepstaylor commented on helm/refresh-db/templates/job.yaml
> +                  name: rds-instance-output
```suggestion
                  name: rds-instance-output-{{ .Values.component }}
```

2024-11-20 21:35 UTC, georgepstaylor commented on helm/refresh-db/templates/job.yaml
> +                  name: rds-instance-output
```suggestion
                  name: rds-instance-output-{{ .Values.component }}
```

2024-11-20 21:35 UTC, georgepstaylor commented on helm/refresh-db/templates/job.yaml
> +                  name: rds-instance-output
```suggestion
                  name: rds-instance-output-{{ .Values.component }}
```

2024-11-20 21:35 UTC, georgepstaylor commented on .github/workflows/delius-core-cp-rds-data-refresh.yaml
> +            --set slackWebhookUrl=${{ secrets.SLACK_WEBHOOK_URL }}
```suggestion
          helm install refresh-db-${{ github.events.inputs.component }} . \
            --set sourceEnvironment=${{ github.event.inputs.source_env }} \
            --set destinationEnvironment=${{ github.event.inputs.destination_env }} \
            --set slackWebhookUrl=${{ secrets.SLACK_WEBHOOK_URL }} \ 
            --set component=${{ github.events.inputs.component }}
```

2024-11-20 21:35 UTC, georgepstaylor commented on .github/workflows/delius-core-cp-rds-data-refresh.yaml
> +        run: helm uninstall refresh-db --ignore-not-found
```suggestion
        run: helm uninstall refresh-db-${{ github.events.inputs.component }} --ignore-not-found
```

2024-11-21 09:59 UTC, georgepstaylor approved these changes

2024-11-21 10:00 UTC, merged